#!/bin/sh -e

gtk-update-icon-cache -f /usr/share/icons/hicolor

oldversion="$2"
if [ -z "$oldversion" ]; then
 maemo-select-menu-location spectool.desktop
fi

chown root /usr/libexec/usbcontrol
chmod +S /usr/libexec/usbcontrol

exit 0

